<?php

use App\User;
use App\Course;
use Illuminate\Database\Seeder;

class DefineCourseIdOnUserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user = User::whereEmail('Maria@courses.pt')->first();
        $user->course_id = Course::whereName('English')->first()->id;
        $user->save();
        $user = User::whereEmail('Ana@courses.pt')->first();
        $user->course_id = Course::whereName('French')->first()->id;
        $user->save();
        $user = User::whereEmail('Sofia@courses.pt')->first();
        $user->course_id = Course::whereName('German')->first()->id;
        $user->save();
        $user = User::whereEmail('Susana@courses.pt')->first();
        $user->course_id = Course::whereName('Chinese')->first()->id;
        $user->save();
        $user = User::whereEmail('Andreia@courses.pt')->first();
        $user->course_id = Course::whereName('Spanish')->first()->id;
        $user->save();
        $user = User::whereEmail('Andre@courses.pt')->first();
        $user->course_id = Course::whereName('C programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Carlos@courses.pt')->first();
        $user->course_id = Course::whereName('C++ programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Helder@courses.pt')->first();
        $user->course_id = Course::whereName('C# programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Micael@courses.pt')->first();
        $user->course_id = Course::whereName('PHP programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Antonio@courses.pt')->first();
        $user->course_id = Course::whereName('Visual Basic programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Ana@hotmail.com')->first();
        $user->course_id = Course::whereName('English')->first()->id;
        $user->save();
        $user = User::whereEmail('Fabiana@hotmail.com')->first();
        $user->course_id = Course::whereName('English')->first()->id;
        $user->save();
        $user = User::whereEmail('Rita@hotmail.com')->first();
        $user->course_id = Course::whereName('English')->first()->id;
        $user->save();
        $user = User::whereEmail('Agostinha@hotmail.com')->first();
        $user->course_id = Course::whereName('English')->first()->id;
        $user->save();
        $user = User::whereEmail('Julieta@hotmail.com')->first();
        $user->course_id = Course::whereName('English')->first()->id;
        $user->save();
        $user = User::whereEmail('Maria@hotmail.com')->first();
        $user->course_id = Course::whereName('French')->first()->id;
        $user->save();
        $user = User::whereEmail('Sofia@hotmail.com')->first();
        $user->course_id = Course::whereName('French')->first()->id;
        $user->save();
        $user = User::whereEmail('Ada@hotmail.com')->first();
        $user->course_id = Course::whereName('French')->first()->id;
        $user->save();
        $user = User::whereEmail('Alexandra@hotmail.com')->first();
        $user->course_id = Course::whereName('French')->first()->id;
        $user->save();
        $user = User::whereEmail('Mariana@hotmail.com')->first();
        $user->course_id = Course::whereName('French')->first()->id;
        $user->save();
        $user = User::whereEmail('Acacia@hotmail.com')->first();
        $user->course_id = Course::whereName('German')->first()->id;
        $user->save();
        $user = User::whereEmail('Amanda@hotmail.com')->first();
        $user->course_id = Course::whereName('German')->first()->id;
        $user->save();
        $user = User::whereEmail('Tatiana@hotmail.com')->first();
        $user->course_id = Course::whereName('German')->first()->id;
        $user->save();
        $user = User::whereEmail('Angelica@hotmail.com')->first();
        $user->course_id = Course::whereName('German')->first()->id;
        $user->save();
        $user = User::whereEmail('Selena@hotmail.com')->first();
        $user->course_id = Course::whereName('German')->first()->id;
        $user->save();
        $user = User::whereEmail('Anastacia@hotmail.com')->first();
        $user->course_id = Course::whereName('Chinese')->first()->id;
        $user->save();
        $user = User::whereEmail('Aurora@hotmail.com')->first();
        $user->course_id = Course::whereName('Chinese')->first()->id;
        $user->save();
        $user = User::whereEmail('Augusta@hotmail.com')->first();
        $user->course_id = Course::whereName('Chinese')->first()->id;
        $user->save();
        $user = User::whereEmail('Telma@hotmail.com')->first();
        $user->course_id = Course::whereName('Chinese')->first()->id;
        $user->save();
        $user = User::whereEmail('Antonia@hotmail.com')->first();
        $user->course_id = Course::whereName('Chinese')->first()->id;
        $user->save();
        $user = User::whereEmail('Carla@hotmail.com')->first();
        $user->course_id = Course::whereName('Spanish')->first()->id;
        $user->save();
        $user = User::whereEmail('Carolina@hotmail.com')->first();
        $user->course_id = Course::whereName('Spanish')->first()->id;
        $user->save();
        $user = User::whereEmail('Madalena@hotmail.com')->first();
        $user->course_id = Course::whereName('Spanish')->first()->id;
        $user->save();
        $user = User::whereEmail('Catarina@hotmail.com')->first();
        $user->course_id = Course::whereName('Spanish')->first()->id;
        $user->save();
        $user = User::whereEmail('Cassandra@hotmail.com')->first();
        $user->course_id = Course::whereName('Spanish')->first()->id;
        $user->save();
        $user = User::whereEmail('Cristiana@hotmail.com')->first();
        $user->course_id = Course::whereName('C programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Judite@hotmail.com')->first();
        $user->course_id = Course::whereName('C programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Mafalda@hotmail.com')->first();
        $user->course_id = Course::whereName('C programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Raquel@hotmail.com')->first();
        $user->course_id = Course::whereName('C programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Diogo@hotmail.com')->first();
        $user->course_id = Course::whereName('C programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Paulo@hotmail.com')->first();
        $user->course_id = Course::whereName('C++ programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Daniel@hotmail.com')->first();
        $user->course_id = Course::whereName('C++ programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Gonçalo@hotmail.com')->first();
        $user->course_id = Course::whereName('C++ programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Joao@hotmail.com')->first();
        $user->course_id = Course::whereName('C++ programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Tiago@hotmail.com')->first();
        $user->course_id = Course::whereName('C++ programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Alberto@hotmail.com')->first();
        $user->course_id = Course::whereName('C# programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Marco@hotmail.com')->first();
        $user->course_id = Course::whereName('C# programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Antonio@hotmail.com')->first();
        $user->course_id = Course::whereName('C# programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Micael@hotmail.com')->first();
        $user->course_id = Course::whereName('C# programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Carlos@hotmail.com')->first();
        $user->course_id = Course::whereName('C# programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Alexandre@hotmail.com')->first();
        $user->course_id = Course::whereName('PHP programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Ronaldo@hotmail.com')->first();
        $user->course_id = Course::whereName('PHP programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Rui@hotmail.com')->first();
        $user->course_id = Course::whereName('PHP programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Claudio@hotmail.com')->first();
        $user->course_id = Course::whereName('PHP programming language')->first()->id;
        $user->save();
        $user = User::whereEmail('Raul@hotmail.com')->first();
        $user->course_id = Course::whereName('PHP programming language')->first()->id;
        $user->save();
    }
}
